blog/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.blogView, name='blog'),
    path('<slug:slug>/', views.blogSingleView, name='blog_single'),
    path('comment', views.comments,  name='comment'),
    path('search', views.search,  name='search'),
    path('newsletter', views.NewsLetter, name='newsletter')
]

blogs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("blog.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from tinymce.models import HTMLField  

# Create your models here.
class Categories(models.Model):
    name = models.CharField(max_length=150)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name
    
class Tag(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name
    


class Blog(models.Model):
    author = models.CharField(max_length=150)
    title = models.CharField(max_length=150)
    slug = models.SlugField(null=False, unique=True)
    thumbnail = models.ImageField(blank=True)
    summary = HTMLField(blank=True)
    content = HTMLField()
    tags = models.ManyToManyField(Tag, blank=True)
    categories = models.ForeignKey(Categories, blank=True, null=True, on_delete=models.SET_NULL)
    date = models.DateTimeField(auto_now_add=True)
    comments_count = models.IntegerField(null=True, blank=True)
    dateUpdated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog_single", kwargs={"slug": self.slug})

    @property
    def imageURL(self):
        try:
            url = self.thumbnail.url
        except:
            url = ''
        return url
    @property
    def comment_count(self):
        try:
            comments_count = self.commnt_set.count()
        except:
            comments_count = 0
        return comments_count
    
class Comment(models.Model):
    name = models.CharField(max_length=150)
    email = models.EmailField(blank=True, null=True)
    message = models.TextField(max_length=1000)
    blog = models.ForeignKey(Blog, blank=True, null=True, on_delete=models.SET_NULL) 
    date = models.DateTimeField(auto_now_add=True)
    validated = models.BooleanField(default=True)
    replyId = models.CharField(max_length=150, blank=True, null=True)

    class Meta:
        ordering = ["-date"]

    def __str__(self):
        return self.name
    

class Newsletter(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email

class Social_Links(models.Model):
    name = models.CharField(max_length=100)
    link = models.URLField()

    def __str__(self):
        return self.name

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import EmptyPage, Paginator
from . models import Blog, Tag, Categories, Comment, Newsletter
from django.db.models import  Q
from django.contrib import messages

# Create your views here.
def blogView(request):
    # infos = Company.objects.order_by('id')[:1]
    # links = Social_Links.objects.all()
    # contacts_infos = Contact_us.objects.order_by('id')[:1]
    blogs = Blog.objects.all().order_by('dateUpdated')
    paginator = Paginator(blogs, 5)
    page = request.GET.get('page')
    paged_blogs = paginator.get_page(page)
    posts = Blog.objects.order_by('-dateUpdated')[:5]
    tags = Tag.objects.all()
    categories = Categories.objects.all()


    # sort_by = request.GET.get('sort', 'l2h')
    # if sort_by == "l2h":
        # blogs = Blog.objects.order_by('-comments_count')
        # for blog in blogs:
        #     print(blog.comments_count)
    
                     
    context = {
        'blogs' :paged_blogs,
        # 'infos' : infos,
        # 'links' : links,
        # 'contacts_infos':contacts_infos,
        'posts' : posts,
        'tags' : tags,
        'categories' : categories
    }
    return render(request, 'blog.html', context)

def search(request):
    # infos = Company.objects.order_by('id')[:1]
    # links = Social_Links.objects.all()
    # contacts_infos = Contact_us.objects.order_by('id')[:1]
    tags = Tag.objects.all()
    categories = Categories.objects.all()
    queryset_list = Blog.objects.order_by('-dateUpdated')
    category_id = request.GET.get('category', 0)
    tag_id = request.GET.get('tag', 0)
    query = request.GET.get('query')
    
    # paginator = Paginator(queryset_list, 2)
    # page = request.GET.get('page')
    # paged_blogs = paginator.get_page(page)
        # Keywords
    
    if query:
        queryset_list = queryset_list.filter(Q(content__icontains=query)| Q(title__icontains=query))
   
    if category_id :
        queryset_list = queryset_list.filter(categories__id=category_id )
    if tag_id :
        queryset_list = queryset_list.filter(tags__id=tag_id )
    
    context ={
        # 'infos' : infos,
        # 'links' : links,
        # 'contacts_infos':contacts_infos,
        'blogs': queryset_list,
        'tags' : tags,
        'categories' : categories,
        "category_id" : int(category_id)
    }
    return render(request, 'search.html', context)

def blogSingleView(request, slug):
    blog = get_object_or_404(Blog, slug=slug)
    blogs = Blog.objects.filter(categories = blog.categories).exclude(id = blog.id)[:5]#reltaed blogs
    tags = Tag.objects.filter(blog__id = blog.id)
    
    comments = blog.comment_set.all()
    context = {
        'blog': blog,
        'blogs' : blogs,
        'comments' : comments,
        'tags' : tags
    }
    return render(request, 'blog-single.html', context)


def comments(request):
    if request.method == 'POST':
        blog_id = request.POST['blog']
        blog = get_object_or_404(Blog, id=blog_id)
        name = request.POST['name']
        email = request.POST['email']
        message = request.POST['comment']

        comment = Comment(name=name, blog = blog, email=email, message=message)
        comment.save()
        messages.success(request, 'comment published successfuly!!')
        return redirect('https://blog.salesflowpro.xyz/' + blog.slug  + '#comment' )

def NewsLetter(request):
    if request.method == 'POST':
        email = request.POST['email']

        newsletter = Newsletter(email=email)
        newsletter.save()
        messages.success(request, 'thanks for subscribing to our newsletter!')
        return redirect('blog')

templates/blog-single.html
{% extends 'main.html' %}
{% load static %}
{% block title%} {{blog.title}} {%endblock title%}
{% block meta%} {{blog.summary|safe}} {%endblock meta%}

{% block content %}

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
      <div class="container mt-2">

        <ol>
          <li><a href="{% url 'blog' %}">Blog</a></li>
          <li>Blog Single</li>
        </ol>
        <h1>{{blog.title}}</h1>

      </div>
    </section><!-- End Breadcrumbs -->

    <!-- ======= Blog Single Section ======= -->
    <section id="blog" class="blog">
      <div class="container" data-aos="fade-up">

        <div class="row">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>


            {% endfor %}
          {% endif %}

          <div class="col-lg-8 entries">

            <article class="entry entry-single">

              <div class="entry-img">
                {% if blog.thumbnail %}
                <img src="{{blog.imageURL}}" class="img-fluid" alt="">
                {% else %}
                <img src="{% static 'assets/img/blog-' %}{{blog.id}}.jpg" style="width: 100%;" class="img-fluid" alt=""/>
                {% endif %}
              </div>

              <!-- <h2 class="entry-title">
                {{blog.title}}
              </h2> -->

              <div class="entry-meta">
                <ul>
                  <li class="d-flex align-items-center"><i class="bi bi-person"></i> {{blog.author}}</li>
                  <li class="d-flex align-items-center"><i class="bi bi-clock"></i><time datetime="2020-01-01">{{ blog.dateUpdated | date}}</time></li>
                  <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a class="nav-link scrollto" href="{%url 'blog' %}#comment">{{blog.comment_set.count}} Comments</a></li>
                </ul>
              </div>

              <div class="entry-content">
                {{blog.content|safe}}

              </div>

              <div class="entry-footer">
                <i class="bi bi-folder"></i>
                <ul class="cats">
                  
                  <li><a href="{% url 'search' %}?query={{ query }}&category={{blog.categories.id}}" title="category">{{blog.categories.name}}</a></li>
                  
                </ul>

                <i class="bi bi-tags"></i>
                <ul class="tags">
                  {%for tag in tags %}
                  <li><a href="{% url 'search' %}?query={{ query }}&tag={{tag.id}}"  title="tag">{{tag.name}}</a></li>
                  {%endfor%}
                  
                </ul>
              </div>

            </article><!-- End blog entry -->

            <!-- <div class="blog-author d-flex align-items-center">
              <img src="assets/img/blog/blog-author.jpg" class="rounded-circle float-left" alt="">
              <div>
                <h4>Jane Smith</h4>
                <div class="social-links">
                  <a href="https://twitters.com/#"><i class="bi bi-twitter"></i></a>
                  <a href="https://facebook.com/#"><i class="bi bi-facebook"></i></a>
                  <a href="https://instagram.com/#"><i class="biu bi-instagram"></i></a>
                </div>
                <p>
                  Itaque quidem optio quia voluptatibus dolorem dolor. Modi eum sed possimus accusantium. Quas repellat voluptatem officia numquam sint aspernatur voluptas. Esse et accusantium ut unde voluptas.
                </p>
              </div>
            </div>End blog author bio -->

            <div class="blog-comments" id="comment">

              <h4 class="comments-count">{{blog.comment_set.count}} Comments</h4>

              {% for comment in comments %}

              <div id="comment-2" class="comment">
                <div class="d-flex">
                  <div>
                    <h5>{{comment.name}} <a class="scrollto reply" href="{%url 'blog' %}#replys" ><i class="bi bi-reply-fill"></i>Reply</a></h5>
                    <time datetime="2020-01-01">{{comment.date}}</time>
                    <p>{{comment.message}}</p>
                  </div>
                </div>

              </div><!-- End comment #2-->
              {%endfor%}

              <div class="reply-form" id="replys">
                <h4>Leave a Comment</h4>
                <p>Your email address will not be published. Required fields are marked * </p>
                <form method="POST" class=""  id="comment" action="{% url 'comment' %}">
                  {% csrf_token %}
                  <div class="row">
                    <div class="visually-hidden">
                      <label for="blog" class="form-label visually-hidden"> blog </label>
                          <select class="form-select" id="floatingSelect" name='blog'aria-label="State">
                              <option value="{{blog.id}}">blog id</option>
                          </select>
                    </div>
                    <div class="col-md-6 form-group">
                      <input name="name" type="text" class="form-control" placeholder="Your Name*" required>
                    </div>
                    <div class="col-md-6 form-group">
                      <input name="email" type="text" class="form-control" placeholder="Your Email*" required>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col form-group">
                      <input name="website" type="text" class="form-control" placeholder="Your Website">
                    </div>
                  </div>
                  <div class="row">
                    <div class="col form-group">
                      <textarea name="comment" class="form-control" placeholder="Your Comment*" required></textarea>
                    </div>
                  </div>
                  <button type="submit" class="btn justify-content-center btn-primary">Post Comment</button>

                </form>
                

              </div>

            </div><!-- End blog comments -->

          </div><!-- End blog entries list -->

          <div class="col-lg-4">

            <div class="sidebar">

              <h3 class="sidebar-title">Related Posts</h3>
              <div class="sidebar-item recent-posts">
                {% for blog in blogs %}
                <div class="post-item clearfix">
                  {% if blog.thumbnail %}
                  <img src="{{blog.imageURL}}" class="img-fluid" alt="">
                  {% else %}
                  <img src="{% static 'assets/img/blog-' %}{{blog.id}}.jpg" style="width: 100%;" class="img-fluid" alt=""/>
                  {% endif %}
                  <h4><a href="{% url 'blog_single' blog.slug %}">{{blog.title}}</a></h4>
                  <time datetime="2020-01-01">{{ blog.dateUpdated }}</time>
                </div>
                {%endfor%}

              </div><!-- End sidebar recent posts-->

            </div><!-- End sidebar -->

          </div><!-- End blog sidebar -->

        </div>

      </div>
    </section><!-- End Blog Single Section -->

  </main><!-- End #main -->
  

 {% endblock %}

templates/blog.html
{%extends "main.html" %}
{% load static %}

{% block title%}Salesflow Pro Blogs {%endblock title%}
{%block content %}

  <main id="main" >

    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
      <div class="container mt-2">

        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>


          {% endfor %}
        {% endif %}

      </div>
    </section>
    <!-- End Breadcrumbs -->

    <!-- ======= Blog Section ======= -->
    <section id="blog" class="blog">
      <div class="container" data-aos="fade-up">

        <div class="row">

          <div class="col-lg-4">

            <div class="sidebar">

              <h3 class="sidebar-title">Search</h3>
              <div class="sidebar-item search-form">
                <form action="{% url 'search' %}">
                  <input type="text" name="query">
                  <button type="submit"><i class="bi bi-search"></i></button>
                </form>
              </div><!-- End sidebar search formn-->

              <h3 class="sidebar-title"><i class="bi bi-folder"></i> Categories</h3>
              <div class="sidebar-item categories">
                <ul>
                  {%for category in categories %}
                  <li id = "category"><a href="{% url 'search' %}?query={{ query }}&category={{category.id}}">{{category.name}} <span>({{category.blog_set.count}})</span></a></li>
                  {%endfor%}
                </ul>
              </div><!-- End sidebar categories-->

              <h3 class="sidebar-title">Recent Posts</h3>
              <div class="sidebar-item recent-posts ">
                {% for post in posts %}
                <div class="post-item clearfix ">
                  {% if blog.thumbnail %}
                  <img src="{{post.imageURL}}" class="img-fluid" alt="">
                  {% else %}
                  <img src="{% static 'assets/img/blog-' %}{{post.id}}.jpg" style="width: 100%;" class="img-fluid" alt=""/>
                  {% endif %}
                  <h4><a href="{% url 'blog_single' post.slug %}">{{post.title}}</a></h4>
                  <time datetime="2020-01-01">{{post.dateUpdated | date}}</time>
                </div>
                {%endfor%}
              </div><!-- End sidebar recent posts-->

              <h3 class="sidebar-title"><i class="bi bi-tags"></i> Tags</h3>
              <div class="sidebar-item tags">
                <ul>
                  {%for tag in tags %}
                  <li><a href="{% url 'search' %}?query={{ query }}&tag={{tag.id}}">{{tag.name}}</a></li>
                  {%endfor%}
                  
                </ul>
              </div><!-- End sidebar tags-->

            </div><!-- End sidebar -->

          </div><!-- End blog sidebar -->

          <div class="col-lg-8 entries">
            {%for blog in blogs %}
            <article class="entry">

              <div class="entry-img">
                {% if blog.thumbnail %}
                <img src="{{blog.imageURL}}" class="img-fluid" alt="">
                {% else %}
                <img src="{% static 'assets/img/blog-' %}{{blog.id}}.jpg" style="width: 100%;" class="img-fluid" alt=""/>
                {% endif %}
              </div>

              <h2 class="entry-title">
                <a href="{% url 'blog_single' blog.slug %}">{{blog.title}}</a>
              </h2>

              <div class="entry-meta">
                <ul>
                  <li class="d-flex align-items-center"><i class="bi bi-person"></i> {{blog.author}}</li>
                  <li class="d-flex align-items-center"><i class="bi bi-clock"></i><time datetime="2020-01-01">{{blog.dateUpdated | date}}</time></li>
                  <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> {{blog.comment_set.count}} Comments</li>
                </ul>
              </div>

              <div class="entry-content">
                <p>{{blog.content|safe|truncatechars:355}}</p>
                <div class="entry-footer">
                  <i class="bi bi-folder"></i>
                  <ul class="cats">
                    
                    <li><a href="{% url 'search' %}?query={{ query }}&category={{blog.categories.id}}" title="category">{{blog.categories.name}}</a></li>
                    
                  </ul>
                </div>
                <div class="read-more">
                  <a href="{% url 'blog_single' blog.slug %}">Read More</a>
                </div>
              </div>

            </article><!-- End blog entry -->
            {%endfor%}

            <!-- paginator -->
            <div class="row">
              <div class="col-md-12 ">
                {% if blogs.has_other_pages %}
                  <ul class="pagination justify-content-center blog-pagination">
                    {% if blogs.has_previous %}
                      <a href="?page={{blogs.previous_page_number}}" class="page-link">&laquo;</a>
                    {% else %}
                      <li class="page-item disabled">
                        <a class="page-link">&laquo;</a>
                      </li>
                    {% endif %}
                    {% for i in blogs.paginator.page_range %}
                      {% if blogs.number == i %}
                        <li class="page-item active">
                          <a class="page-link">{{ i }}</a>
                        </li>
                      {% else %}
                        <li class="page-item">
                          <a href="?page={{i}}" class="page-link">{{ i }}</a>
                        </li>
                      {% endif %}
                    {% endfor %}
                    {% if blogs.has_next %}
                      <a href="?page={{ blogs.next_page_number }}" class="page-link">&raquo;</a>
                    {% else %}
                      <li class="page-item disabled">
                        <a class="page-link">&raquo;</a>
                      </li>
                    {% endif %}
                  </ul>
                {% endif %}
              </div>
            </div>

          </div><!-- End blog entries list -->

        </div>

      </div>
    </section><!-- End Blog Section -->

  </main><!-- End #main -->
  

  {% endblock %}
  
  

templates/search.html
{%extends "main.html" %}
{% load static %}

{% block title%} Blog Search {%endblock title%}
{%block content %}

  <main id="main" >

    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
      <div class="container mt-2">

        <ol>
          <li><a href="{% url 'blog' %}">Blog</a></li>
        </ol>
        <h2>Search Results</h2>

      </div>
    </section><!-- End Breadcrumbs -->

    <!-- ======= Blog Section ======= -->
    <section id="blog" class="blog">
      <div class="container" data-aos="fade-up">

        <div class="row">
            
          <div class="col-lg-4">


            <div class="sidebar">

              <h3 class="sidebar-title">Search</h3>
              <div class="sidebar-item search-form">
                <form action="{% url 'search' %}">
                  <input type="text" name="query" placeholder="search">
                  <button type="submit"><i class="bi bi-search"></i></button>
                </form>
              </div><!-- End sidebar search formn-->

              <h3 class="sidebar-title"><i class="bi bi-folder"></i> Categories</h3>
              <div class="sidebar-item categories">
                <ul>
                  {%for category in categories %}
                  <li id = "category"><a href="{% url 'search' %}?query={{ query }}&category={{category.id}}">{{category.name}} <span>({{category.blog_set.count}})</span></a></li>
                  {%endfor%}
                </ul>
              </div><!-- End sidebar categories-->

              <h3 class="sidebar-title"><i class="bi bi-tags"></i> Tags</h3>
              <div class="sidebar-item tags">
                <ul>
                  {%for tag in tags %}
                  <li><a href="{% url 'search' %}?query={{ query }}&tag={{tag.id}}">{{tag.name}}</a></li>
                  {% endfor %}
                  
                </ul>
              </div><!-- End sidebar tags-->

            </div><!-- End sidebar -->

          </div><!-- End blog sidebar -->

          <div class="col-lg-8 entries">
            {%if blogs %}
            {%for blog in blogs %}
            <article class="entry">

              <div class="entry-img">
                {% if blog.thumbnail %}
                <img src="{{blog.imageURL}}" class="img-fluid" alt="">
                {% else %}
                <img src="{% static 'assets/img/blog-' %}{{blog.id}}.jpg" style="width: 100%;" class="img-fluid" alt=""/>
                {% endif %}
              </div>

              <h2 class="entry-title">
                <a href="{% url 'blog_single' blog.slug %}">{{blog.title}}</a>
              </h2>

              <div class="entry-meta">
                <ul>
                  <li class="d-flex align-items-center"><i class="bi bi-person"></i> {{blog.author}}</li>
                  <li class="d-flex align-items-center"><i class="bi bi-clock"></i><time datetime="2020-01-01">{{blog.dateUpdated |date}}</time></li>
                  <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> {{blog.comment_set.count}} Comments</li>
                </ul>
              </div>

              <div class="entry-content">
                <p>{{blog.content|truncatechars:455 |safe}}</p>
                <div class="entry-footer">
                    <i class="bi bi-folder"></i>
                    <ul class="cats">
                      
                      <li><a href="{% url 'search' %}?query={{ query }}&category={{category.id}}">{{blog.categories.name}}</a></li>
                      
                    </ul>
    
                    <i class="bi bi-tags"></i>
                    <ul class="tags">
                      
                      <li><a href="#">tag</a></li>
                      
                    </ul>
                  </div>
                <div class="read-more">
                  <a href="{% url 'blog_single' blog.slug %}">Read More</a>
                </div>
              </div>

            </article><!-- End blog entry -->
            {%endfor%}

            <!-- paginator
            <div class="row">
              <div class="col-md-12 ">
                {% if blogs.has_other_pages %}
                  <ul class="pagination justify-content-center blog-pagination">
                    {% if blogs.has_previous %}
                      <a href="?page={{blogs.previous_page_number}}" class="page-link">&laquo;</a>
                    {% else %}
                      <li class="page-item disabled">
                        <a class="page-link">&laquo;</a>
                      </li>
                    {% endif %}
                    {% for i in blogs.paginator.page_range %}
                      {% if blogs.number == i %}
                        <li class="page-item active">
                          <a class="page-link">{{ i }}</a>
                        </li>
                      {% else %}
                        <li class="page-item">
                          <a href="?page={{i}}" class="page-link">{{ i }}</a>
                        </li>
                      {% endif %}
                    {% endfor %}
                    {% if blogs.has_next %}
                      <a href="?page={{ blogs.next_page_number }}" class="page-link">&raquo;</a>
                    {% else %}
                      <li class="page-item disabled">
                        <a class="page-link">&raquo;</a>
                      </li>
                    {% endif %}
                  </ul>
                {% endif %}
              </div>
            </div> -->
            {%else%}
            <div class="col-8 justify-content-center">
                <h6>No Match Results !!!</h6>
            </div>
            {%endif%}

          </div><!-- End blog entries list -->

        </div>

      </div>
    </section><!-- End Blog Section -->

  </main><!-- End #main -->

  {% endblock %}
  